# A CI configuration to auto-publish pub packages.
name: Dart CI Publish # publish to pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: ''

permissions:
  id-token: write

  # Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: pub.dev
    #   working-directory: path/to/package/within/repository